repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
        exclude: '\.jsonl$'
      - id: check-added-large-files
        args: ["--maxkb=1024"]

  - repo: local
    hooks:
      - id: check-jsonl
        name: check-jsonl
        entry: python3 scripts/check_jsonl.py
        language: system
        files: '\.jsonl$'
        exclude: '\.jsonl\.out$'

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        args: ["--fix"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff-format
        types_or: [jupyter]
